services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trading_platform_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - trading_platform_network

networks:
  trading_platform_network:
    name: trading_platform_network
    driver: bridge
    external: true
