services:
  db_test:
    image: postgres:18.6-trixie
    container_name: Endgame_TEST_DB
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: Endgame_TEST_DB

    ports:
      - "5532:5432"

    volumes:
      - ~/.asset_postgres_test_data:/var/lib/postgresql

