spring.application.name=Endgame
server.port=8082
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

pricing.api.base-url=${PRICING_API_BASE_URL:https://y4t9nq2bqf.execute-api.eu-west-2.amazonaws.com}
pricing.api.key=${FAUXNANCE_KEY:}
pricing.api.quotes-path=${PRICING_API_QUOTES_PATH:/v1/quotes}
