spring.application.name=Endgame
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5555/asset-avengers-client
spring.datasource.username=postgres
spring.datasource.password=asseta26
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true